cargo-features = ["workspace-inheritance"]

[package]
name = "deposit"
version = "0.1.0"
edition = "2021"

[dependencies.fvm_shared]
workspace = true

[dependencies.cid]
workspace = true

[dependencies.thiserror]
workspace = true

[build-dependencies]
substrate-wasm-builder = "4.0.0"
